### ISSUE TITLE
Setting tags for each link

### ISSUE THREAD

**Issue by thehand** [cirpo/hubot-save-links#12]
Let the user specify tags for the link he's posting, maybe using the classic "#" after the link, hubot-save-links will parse the messagge and will store each #word as a tag.

**Comment by MicheleBertoli** [comment]
@cirpo this is already working, isn't it?

**Comment by cirpo** [comment]
yes and no, the thing is that with the current redis structure you can't say "hey dude, gimme all the #tdd links". I'm going to leave this opened as reference.

**Comment by cirpo** [comment]
@MicheleBertoli with the latest version, 0.0.24, we also have an api that expose links by tag: /links/tag/{tag}
