### ISSUE TITLE
Edited links

### ISSUE THREAD

**Issue by MicheleBertoli** [cirpo/hubot-save-links#30]
If a user posts a link and then edits it, it would be nice to update the entry in the database.

For example, @sandropaganotti edited his post:

<img width="799" alt="screen shot 2015-07-26 at 18 11 35" src="https://cloud.githubusercontent.com/assets/1308971/8894987/b1ee3620-33c1-11e5-9e0d-5f713b691e40.png">

But we still have the old url:

```
{
  "link": "https://adventure-sandro-paganotti.c9.io/adventure.html",
  "postedBy": "sandro",
  "date": 1437924644282,
  "parsedUrl": {
    "protocol": "https:",
    "slashes": true,
    "auth": null,
    "host": "adventure-sandro-paganotti.c9.io",
    "port": null,
    "hostname": "adventure-sandro-paganotti.c9.io",
    "hash": null,
    "search": null,
    "query": null,
    "pathname": "/adventure.html",
    "path": "/adventure.html",
    "href": "https://adventure-sandro-paganotti.c9.io/adventure.html"
  },
  "tags": null,
  "room": "developers"
}
```

**Comment by pasine** [comment]
The problem is not in the bot, but in the adapter that doesn't handle edited messages.
I tried a fix. Feel free to test it and see if it works.
https://github.com/pasine/hubot-slack/tree/edited-msg

p.s.
this doesn't fix the issue anyway. The message still need to be handled properly by the bot.
